version: "3.1"

networks:
  backend:
    name: vibex-api
    driver: bridge

volumes:
  database:
    name: vibex-api-database

services:
  postgres:
    container_name: vibex-postgress
    image: postgres:16
    environment:
      POSTGRES_USER: ${VIBEX_PG_USER}
      POSTGRES_PASSWORD: ${VIBEX_PG_PWD}
      POSTGRES_DB: ${VIBEX_PG_DB}
    ports:
      - ${VIBEX_PG_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
